server:
    tomcat:
        uri-encoding: UTF-8
    port: 8082
spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jackson:
        default-property-inclusion: non_null
    messages:
        encoding: UTF-8
udp:
    port: 9998
    threadCount:  2
    ip: 192.168.3.55